CREATE TABLE IF NOT EXISTS vehicles (
    vehicle_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate_number VARCHAR(20) NOT NULL UNIQUE,
    owner_name VARCHAR(100) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_vehicles_plate_number ON vehicles (plate_number);

CREATE TABLE IF NOT EXISTS parking_zones (
    zone_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_code VARCHAR(10) NOT NULL UNIQUE,
    zone_name VARCHAR(100) NOT NULL,
    hourly_rate NUMERIC(6,2) NOT NULL CHECK (hourly_rate >= 0),
    max_parking_minutes INTEGER NOT NULL CHECK (max_parking_minutes > 0)
);

CREATE TABLE IF NOT EXISTS parking_spaces (
    space_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_number VARCHAR(20) NOT NULL UNIQUE,
    zone_id INTEGER NOT NULL REFERENCES parking_zones (zone_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    street_name VARCHAR(100),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_spaces_space_number ON parking_spaces (space_number);

CREATE TABLE IF NOT EXISTS parking_events (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id INTEGER NOT NULL REFERENCES vehicles (vehicle_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    space_id INTEGER NOT NULL REFERENCES parking_spaces (space_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    customer_id VARCHAR(32),
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NULL,
    status VARCHAR(20) NOT NULL,
    calculated_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE parking_events ADD COLUMN IF NOT EXISTS customer_id VARCHAR(32);
CREATE INDEX IF NOT EXISTS idx_events_customer_active ON parking_events (customer_id, status) WHERE end_time IS NULL;

CREATE TABLE IF NOT EXISTS payment_transactions (
    transaction_id VARCHAR(64) PRIMARY KEY,
    event_id INTEGER NOT NULL REFERENCES parking_events (event_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    vehicle_id INTEGER NOT NULL REFERENCES vehicles (vehicle_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    space_id INTEGER NOT NULL REFERENCES parking_spaces (space_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    zone_code VARCHAR(10) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    stop_time TIMESTAMP NOT NULL,
    amount NUMERIC(10,2) NOT NULL CHECK (amount >= 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_payment_transactions_vehicle_id ON payment_transactions (vehicle_id);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_stop_time ON payment_transactions (stop_time DESC);

CREATE TABLE IF NOT EXISTS citations (
    citation_id VARCHAR(64) PRIMARY KEY,
    vehicle_id INTEGER NOT NULL REFERENCES vehicles (vehicle_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    space_id INTEGER NOT NULL REFERENCES parking_spaces (space_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    zone_code VARCHAR(10) NOT NULL,
    inspection_time TIMESTAMP NOT NULL,
    amount NUMERIC(10,2) NOT NULL CHECK (amount > 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_citations_vehicle_id ON citations (vehicle_id);
CREATE INDEX IF NOT EXISTS idx_citations_inspection_time ON citations (inspection_time DESC);

CREATE TABLE IF NOT EXISTS customers (
    customer_id VARCHAR(32) PRIMARY KEY,
    vehicle_id INTEGER UNIQUE REFERENCES vehicles (vehicle_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    display_name VARCHAR(100) NOT NULL,
    password_hash VARCHAR(128) NOT NULL,
    password_salt VARCHAR(64) NOT NULL,
    password_iterations INTEGER NOT NULL CHECK (password_iterations > 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE customers ADD COLUMN IF NOT EXISTS vehicle_id INTEGER UNIQUE REFERENCES vehicles (vehicle_id) ON UPDATE CASCADE ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_customers_vehicle_id ON customers (vehicle_id);

INSERT INTO customers (customer_id, vehicle_id, display_name, password_hash, password_salt, password_iterations, is_active)
VALUES
    ('CUST-1001', (SELECT vehicle_id FROM vehicles WHERE plate_number = '604-95-839'), 'Customer One', 'fe0b1603910880a265f613cba12d1386a38c128573d8b8e05a44d2176ff2a4f4', 'c1ebf599ba489f3869442f2087a95d98', 120000, TRUE),
    ('CUST-1002', (SELECT vehicle_id FROM vehicles WHERE plate_number = '089-64-318'), 'Customer Two', '5291c8a3d5efc839c9a1e9c2c462ee2ddb9e99de8c24cac544cecaedc7d328ea', '1ccb4fb19c1887b57a71f93b501c53ae', 120000, TRUE),
    ('CUST-1003', (SELECT vehicle_id FROM vehicles WHERE plate_number = '058-28-878'), 'Customer Three', '3d54531654d8fefddcd7d3371680980985cbbbcff5b4c9ac306fcec22fbeff0c', '4cba9cbe0f32e7351b823bb196df0c57', 120000, TRUE),
    ('CUST-1004', (SELECT vehicle_id FROM vehicles WHERE plate_number = '394-23-797'), 'Customer Four', '3d6c8a14089d21b3a785067d230c484d0683cc298e8c4e43b3edddfcd44391e4', '051d18dd51a7df5247cc1935ff991a11', 120000, TRUE)
ON CONFLICT (customer_id) DO UPDATE SET
    vehicle_id = EXCLUDED.vehicle_id;

CREATE TABLE IF NOT EXISTS mo_users (
    user_id VARCHAR(32) PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    password_hash VARCHAR(128) NOT NULL,
    password_salt VARCHAR(64) NOT NULL,
    password_iterations INTEGER NOT NULL CHECK (password_iterations > 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO mo_users (user_id, display_name, password_hash, password_salt, password_iterations, is_active)
VALUES
    ('MO-1001', 'MO User One', 'f0e602a7cf1d8b9c2d23bef6e159f1580c77c66dd5fd69305d98bcbfbf9b9068', '50177e7c71848ab741a8a02d2e28740c', 120000, TRUE),
    ('MO-1002', 'MO User Two', '4b1873875d2ee91b7e7d32b1ba688c8156ce2fce0929f7a102a1e3e0aff3b788', '2b6014db29a2b9e4b0cd9b2cf033f528', 120000, TRUE),
    ('MO-1003', 'MO User Three', 'fce0a09d883967b58eac790687a314db8dcdbac64235f175174752f346b834c7', '9f08d807a00024db4adb5668a1e40f74', 120000, TRUE),
    ('MO-1004', 'MO User Four', 'cf22b07065aa5dd5a3ff18447f9c6dd99f6bd0399255d0f6087f30d93915457c', '55a7f801c8fa9e462f9d9a5c0130ed5e', 120000, TRUE)
ON CONFLICT (user_id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    password_hash = EXCLUDED.password_hash,
    password_salt = EXCLUDED.password_salt,
    password_iterations = EXCLUDED.password_iterations,
    is_active = EXCLUDED.is_active;

CREATE TABLE IF NOT EXISTS peo_users (
    user_id VARCHAR(32) PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    password_hash VARCHAR(128) NOT NULL,
    password_salt VARCHAR(64) NOT NULL,
    password_iterations INTEGER NOT NULL CHECK (password_iterations > 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO peo_users (user_id, display_name, password_hash, password_salt, password_iterations, is_active)
VALUES
    ('PEO-1001', 'PEO User One', 'a5c63b0d0e96249657c9179f383f05c0eaad916badaa64aab8955cf8149286d3', 'e7ae1ab718f992f797238687e91469f6', 120000, TRUE),
    ('PEO-1002', 'PEO User Two', '5a41fcaadcb56a83ae938d881e3c3dad25820c2877466fc405c90b069d859544', 'b88c3749f0d0137b39b7fee6acb564a8', 120000, TRUE),
    ('PEO-1003', 'PEO User Three', 'a576bb78f5adf21ff1a95aca43f1e7ef8c8793732a5f0f636efb1589adbc8c04', 'b726993f33dfe82a096886b4545fe8d7', 120000, TRUE),
    ('PEO-1004', 'PEO User Four', '645830426e1f28ecb409e4f4f91346c2fe2c056290421c5fbce7e4fb87830619', '1728a450d8474055bfdc7e7c2367221c', 120000, TRUE)
ON CONFLICT (user_id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    password_hash = EXCLUDED.password_hash,
    password_salt = EXCLUDED.password_salt,
    password_iterations = EXCLUDED.password_iterations,
    is_active = EXCLUDED.is_active;

INSERT INTO parking_zones (zone_code, zone_name, hourly_rate, max_parking_minutes)
VALUES
    ('A1', 'Central Zone', 8.00, 120),
    ('A2', 'Mall Zone', 10.00, 180),
    ('B1', 'Residential North', 5.50, 240),
    ('B2', 'Residential South', 6.00, 240),
    ('C1', 'Hospital Zone', 7.50, 90),
    ('C2', 'University Zone', 4.50, 300),
    ('D1', 'Beach Zone', 12.00, 180),
    ('D2', 'Business District', 11.00, 120),
    ('E1', 'Old City', 9.00, 150),
    ('E2', 'Train Station', 6.50, 60)
ON CONFLICT (zone_code) DO NOTHING;

INSERT INTO vehicles (plate_number, owner_name)
VALUES
    ('604-95-839', 'Nora Levin'),
    ('089-64-318', 'Omer Cohen'),
    ('058-28-878', 'Maya Azulay'),
    ('394-23-797', 'Daniel Shalev'),
    ('487-36-686', 'Lior Green'),
    ('682-14-762', 'Roni Katz'),
    ('513-77-315', 'Yael Mor'),
    ('233-47-038', 'Amit Ben David'),
    ('412-60-971', 'Tamar Klein'),
    ('286-66-320', 'Noam Peretz')
ON CONFLICT (plate_number) DO NOTHING;

UPDATE customers
SET vehicle_id = assigned.vehicle_id
FROM (
    VALUES
        ('CUST-1001', '604-95-839'),
        ('CUST-1002', '089-64-318'),
        ('CUST-1003', '058-28-878'),
        ('CUST-1004', '394-23-797')
) AS mapping(customer_id, plate_number)
JOIN vehicles assigned ON assigned.plate_number = mapping.plate_number
WHERE customers.customer_id = mapping.customer_id;

INSERT INTO parking_spaces (space_number, zone_id, street_name, is_active)
SELECT
    'S' || LPAD((((zone_seed.zone_rank - 1) * 10) + slot.slot_number)::TEXT, 3, '0'),
    zone_seed.zone_id,
    zone_seed.zone_name || ' Street',
    TRUE
FROM (
    SELECT zone_id, zone_name, ROW_NUMBER() OVER (ORDER BY zone_code) AS zone_rank
    FROM parking_zones
) AS zone_seed
CROSS JOIN (
    SELECT generate_series(1, 10) AS slot_number
) AS slot
ON CONFLICT (space_number) DO NOTHING;
