package com.mulligan.common.security;

import javax.net.ssl.KeyManagerFactory;
import javax.net.ssl.SSLContext;
import javax.net.ssl.TrustManagerFactory;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.KeyStore;

/**
 * Builds a JSSE {@link SSLContext} for TLS 1.2/1.3 with optional mutual
 * authentication. The same context is reused for AMQPS to RabbitMQ and
 * (optionally) for inter-service trust of the JDBC connection's truststore.
 *
 * <p>Configuration order of precedence:
 * <ol>
 *   <li>{@code mulligan.tls.truststore}, {@code mulligan.tls.truststore.password}</li>
 *   <li>{@code MULLIGAN_TLS_TRUSTSTORE}, {@code MULLIGAN_TLS_TRUSTSTORE_PASSWORD}</li>
 * </ol>
 *
 * <p>Same pair for keystore: {@code mulligan.tls.keystore}, {@code
 * mulligan.tls.keystore.password} (optional; required only for mTLS).
 *
 * <p>If the truststore is missing the context uses the JVM default trust
 * material — convenient for local development. The Defense.md report
 * documents how to swap that for the mTLS keystore generated by
 * {@code infra/certs/generate-certs.sh} in production.
 */
public final class TlsConfig {

    private TlsConfig() {
    }

    /**
     * Builds an {@link SSLContext} suitable for AMQPS.
     *
     * @return SSL context honoring the env/system property configuration
     */
    public static SSLContext buildAmqpsContext() {
        try {
            KeyManagerFactory kmf = null;
            String keystorePath = resolve("mulligan.tls.keystore", "MULLIGAN_TLS_KEYSTORE");
            String keystorePass = resolve("mulligan.tls.keystore.password", "MULLIGAN_TLS_KEYSTORE_PASSWORD");
            if (keystorePath != null && !keystorePath.isBlank()) {
                KeyStore ks = loadStore(keystorePath, keystorePass);
                kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
                kmf.init(ks, keystorePass == null ? new char[0] : keystorePass.toCharArray());
            }

            TrustManagerFactory tmf = null;
            String truststorePath = resolve("mulligan.tls.truststore", "MULLIGAN_TLS_TRUSTSTORE");
            String truststorePass = resolve("mulligan.tls.truststore.password", "MULLIGAN_TLS_TRUSTSTORE_PASSWORD");
            if (truststorePath != null && !truststorePath.isBlank()) {
                KeyStore ts = loadStore(truststorePath, truststorePass);
                tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
                tmf.init(ts);
            }

            SSLContext ctx = SSLContext.getInstance("TLSv1.2");
            ctx.init(
                kmf == null ? null : kmf.getKeyManagers(),
                tmf == null ? null : tmf.getTrustManagers(),
                null
            );
            return ctx;
        } catch (Exception e) {
            throw new IllegalStateException("Unable to build TLS context: " + e.getMessage(), e);
        }
    }

    /**
     * Returns the value of the JDBC {@code ssl=true} query parameter that
     * should be appended to the JDBC URL. Returns an empty string when TLS is
     * disabled (used for local non-Docker development).
     *
     * @return JDBC TLS query string (with leading {@code &} when present) or empty string
     */
    public static String jdbcTlsParameters() {
        String enabled = resolve("mulligan.db.tls", "MULLIGAN_DB_TLS");
        if (enabled == null || enabled.isBlank() || enabled.equalsIgnoreCase("false")) {
            return "";
        }
        // PostgreSQL JDBC driver expects ssl=true plus an explicit mode.
        return "&ssl=true&sslmode=require";
    }

    private static KeyStore loadStore(String path, String password) throws Exception {
        KeyStore ks = KeyStore.getInstance(path.endsWith(".p12") || path.endsWith(".pfx") ? "PKCS12" : "JKS");
        try (InputStream in = Files.newInputStream(Path.of(path))) {
            ks.load(in, password == null ? null : password.toCharArray());
        }
        return ks;
    }

    private static String resolve(String prop, String env) {
        String value = System.getProperty(prop);
        if (value == null || value.isBlank()) {
            value = System.getenv(env);
        }
        return value;
    }
}
